Inline support branch
Piterden/chessbot pull request #11
Opened 2019-04-22 19:10 UTC by kolay-v

2019-04-22 19:17 UTC, Piterden requested changes

2019-04-22 19:17 UTC, Piterden commented on knexfile.js
>  require('dotenv').load()
Эту строчку тоже в `src/knex-config` надо.

2019-04-22 19:17 UTC, Piterden commented on knexfile.js
> +module.exports = require('./src/knex_config')
Надо через дефис

2019-04-22 19:17 UTC, Piterden commented on package.json
> +    "dev": "nodemon -w src src/index.js"
Вот это зря так делаешь, он может ругаться на несовпадение версий с глобально стоящим!!!

2019-04-22 19:17 UTC, Piterden commented on src/knex_config.js
> +}
```js
const production = {
  client: 'pg',
  connection: {
    database: DB_DATABASE,
    user: DB_USERNAME,
    password: DB_PASSWORD,
    charset: DB_CHARSET,
  },
  pool: {
    min: 2,
    max: 10,
  },
  migrations: {
    tableName: DB_MIGRATIONS_TABLE,
  },
}

 const development = {
  client: 'sqlite3',
  connection: {
    filename: DB_DATABASE,
    charset: DB_CHARSET,
  },
  migrations: {
    tableName: DB_MIGRATIONS_TABLE,
  },
}

 const config = {
  development,
  production,
}
```

2019-04-22 19:20 UTC, kolay-v commented on knexfile.js
>  require('dotenv').load()
Не загружается dotenv в этом файле, потому что при импорте из index.js он уже зашоужен

2019-04-22 19:22 UTC, kolay-v commented on package.json
> +    "dev": "nodemon -w src src/index.js"
Он автоматически использует установленный локально.

2019-04-24 05:08 UTC, Piterden approved these changes

2019-04-24 05:10 UTC, merged